---
- hosts: all
  become: yes

  tasks:
    - name: Pass SSH Keys to target hosts
      authorized_key: 
        user: ansible
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"